project:
  type: website

website:
  title: "BPM4RC"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - text: "SLR"
        href: https://github.com/jan-ru/yr2_slr/index.html
      - text: "Abstracts"
        href: https://github.com/jan-ru/yr2_abstracts/index.html
      - text: "Scripts"
        href: https://github.com/jan-ru/yr2_interviews/index.html
#      - text: "Slides"
#        href: about.qmd#slides          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



