project:
  type: website

website:
  title: "BPM4RC"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - text: "SLR"
        href: books/slr/index.html
      - text: "Abstracts"
        href: page_02_abstracts.qmd
      - text: "Scripts"
        href: ./index2.html
#      - text: "Slides"
#        href: about.qmd#slides          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



