project:
  type: website

website:
  title: "Vlerick Dba"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "SLR"
        href: page_01_slr.qmd
      - text: "Abstracts"
        href: page_02_abstracts.qmd
#      - text: "Scripts"
#        href: ./scripts/index.html
#      - text: "Slides"
#        href: about.qmd#slides          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



