project:
  type: website

website:
  title: "BPM4RC"
  navbar:
    search: false
    left:
      - text: "Review"
        href: https://jan-ru.github.io/yr2_slr
      - text: "Articles"
        href: https://jan-ru.github.io/yr2_abstract
      - text: "Abstracts"
        href: https://jan-ru.github.io/yr2_abstracts
      - text: "Searches"
        href: https://jan-ru.github.io/yr2_abstracts
      - text: "Scripts"
        href: https://jan-ru.github.io/yr2_software

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true