project:
  type: website

website:
  title: "BPM4RC"
  navbar:
    search: false
    left:
#      - href: index.qmd
#        text: Home
      - text: "SLR"
        href: https://jan-ru.github.io/yr2_slr/index.html
      - text: "Abstracts"
        href: https://jan-ru.github.io/yr2_abstracts/index.html
      - text: "Scripts"
        href: https://jan-ru.github.io/yr2_software/scripts/index.html
#      - text: "Slides"
#        href: about.qmd#slides          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



